name: Check Migrations Again
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      # copy code from repo into container
      - uses: actions/checkout@v2
      # run migration validation bash script
      - name: Do Thing
        run: if [ -f conflict.py ]; then echo "conflict"; exit 1; fi
