name: Run a script
on:
  # run for every push to master
  push:
    branches:
      - main
  # run for every PR targeted at master
  pull_request:
    branches:
      - main

  pull_request_target:
    types:
      - closed

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # copy code from repo into container
      - uses: actions/checkout@v2
      # run migration validation bash script
      - name: Do Thing
        run: echo "normal"

  if_merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == 'true'
    steps:
      # copy code from repo into container
      - uses: actions/checkout@v2
      # run migration validation bash script
      - name: Do Thing
        run: echo "on merge"
