name: Check Migrations Again
on:
  # run for every push to master
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      # copy code from repo into container
      - uses: actions/checkout@v2
      # run migration validation bash script
      - name: Do Thing
        run: if [ -f conflict.py ]; then echo "conflict" exit 1; fi
